services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photobooth-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - photobooth-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

  nginx:
    image: nginx:alpine
    container_name: photobooth-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - photobooth-network
    depends_on:
      - app

networks:
  photobooth-network:
    driver: bridge
